In [ ]:
!pip list

Package                                  Version
---------------------------------------- ------------------
absl-py                                  1.4.0
accelerate                               1.13.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.2
aiohttp                                  3.14.1
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.12.0
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.13.0
anywidget                                0.9.21
apsw                                     3.53.2.0
apswutils                                0.1.2
argon2-cffi                              25.1.0
argon2-cffi-bindings                     25.1.0
array_record                             0.8.3
arrow                                    1.4.0
arviz                                    0.22.0
astropy                                  7.2.0
astropy-iers-data                        0.2026.6.8.17.49.5
astunparse                               1.6.3
atpublic                                 5.1
attrs                                    26.1.0
audioread                                3.1.0
Authlib                                  1.7.2
autograd                                 1.8.0
babel                                    2.18.0
backcall                                 0.2.0
beartype                                 0.22.9
beautifulsoup4                           4.13.5
betterproto                              2.0.0b6
bigframes                                2.42.0
bigquery-magics                          0.14.0
bleach                                   6.4.0
blinker                                  1.9.0
blis                                     1.3.3
blobfile                                 3.2.0
blosc2                                   4.4.2
bokeh                                    3.8.2
Bottleneck                               1.4.2
bqplot                                   0.12.47
branca                                   0.8.2
brotli                                   1.2.0
CacheControl                             0.14.4
cachetools                               6.2.6
catalogue                                2.0.10
certifi                                  2026.5.20
cffi                                     2.0.0
chardet                                  5.2.0
charset-normalizer                       3.4.7
clarabel                                 0.11.1
click                                    8.4.1
cligj                                    0.7.2
cloudpathlib                             0.24.0
cloudpickle                              3.1.2
cmake                                    3.31.10
cmdstanpy                                1.3.0
colorcet                                 3.2.1
colorlover                               0.3.0
community                                1.0.0b1
confection                               1.3.3
cons                                     0.4.7
contourpy                                1.3.3
cramjam                                  2.11.0
cryptography                             48.0.1
cufflinks                                0.17.3
curl_cffi                                0.15.0
cvxopt                                   1.3.2
cvxpy                                    1.6.7
cycler                                   0.12.1
cyipopt                                  1.5.0
cymem                                    2.0.13
Cython                                   3.0.12
dask                                     2026.3.0
dataproc-spark-connect                   1.1.0
datasets                                 4.0.0
db-dtypes                                1.7.0
dbus-python                              1.2.18
debugpy                                  1.8.15
decorator                                4.4.2
defusedxml                               0.7.1
deprecation                              2.1.0
diffusers                                0.38.0
dill                                     0.3.8
distro                                   1.9.0
dlib                                     19.24.6
dm-tree                                  0.1.10
docstring_parser                         0.18.0
docutils                                 0.21.2
dopamine_rl                              4.1.2
duckdb                                   1.3.2
earthengine-api                          1.7.30
easydict                                 1.13
editdistance                             0.8.1
eerepr                                   0.1.2
einops                                   0.8.2
en_core_web_sm                           3.8.0
entrypoints                              0.4
esda                                     2.9.0
et_xmlfile                               2.0.0
etils                                    1.14.0
etuples                                  0.3.10
Farama-Notifications                     0.0.6
fastai                                   2.8.7
fastapi                                  0.136.3
fastcore                                 1.13.3
fastdownload                             0.0.7
fastjsonschema                           2.21.2
fastlite                                 0.2.4
fastprogress                             1.1.6
fasttransform                            0.0.2
ffmpy                                    1.0.0
filelock                                 3.29.2
firebase-admin                           6.9.0
Flask                                    3.1.3
flatbuffers                              25.12.19
flax                                     0.11.2
folium                                   0.20.0
fonttools                                4.63.0
fqdn                                     1.5.1
frozendict                               2.4.7
frozenlist                               1.8.0
fsspec                                   2025.3.0
future                                   1.0.0
gast                                     0.7.0
gcsfs                                    2025.3.0
GDAL                                     3.8.4
gdown                                    5.2.2
geemap                                   0.38.0
geocoder                                 1.38.1
geographiclib                            2.1
geopandas                                1.1.3
geopy                                    2.4.1
giddy                                    2.3.6
gin-config                               0.5.0
gitdb                                    4.0.12
GitPython                                3.1.50
glob2                                    0.7
google                                   3.0.0
google-adk                               1.29.0
google-ai-generativelanguage             0.6.15
google-api-core                          2.30.3
google-api-python-client                 2.197.0
google-auth                              2.47.0
google-auth-httplib2                     0.4.0
google-auth-oauthlib                     1.4.0
google-cloud-aiplatform                  1.157.0
google-cloud-appengine-logging           1.10.0
google-cloud-audit-log                   0.6.0
google-cloud-bigquery                    3.41.0
google-cloud-bigquery-connection         1.22.0
google-cloud-bigquery-storage            2.39.0
google-cloud-bigtable                    2.38.0
google-cloud-core                        2.6.0
google-cloud-dataplex                    2.20.0
google-cloud-dataproc                    5.28.0
google-cloud-datastore                   2.25.0
google-cloud-discoveryengine             0.13.12
google-cloud-firestore                   2.27.0
google-cloud-functions                   1.23.0
google-cloud-iam                         2.23.0
google-cloud-language                    2.20.0
google-cloud-logging                     3.16.0
google-cloud-monitoring                  2.31.0
google-cloud-pubsub                      2.39.0
google-cloud-resource-manager            1.17.0
google-cloud-secret-manager              2.29.0
google-cloud-spanner                     3.67.0
google-cloud-speech                      2.40.0
google-cloud-storage                     3.11.0
google-cloud-trace                       1.19.0
google-cloud-translate                   3.26.0
google-colab                             1.0.0
google-crc32c                            1.8.0
google-genai                             1.68.0
google-generativeai                      0.8.6
google-pasta                             0.2.0
google-resumable-media                   2.10.0
googleapis-common-protos                 1.75.0
googledrivedownloader                    1.1.0
gradio                                   5.50.0
gradio_client                            1.14.0
grain                                    0.2.17
graphviz                                 0.21
greenlet                                 3.5.1
groovy                                   0.1.2
grpc-google-iam-v1                       0.14.4
grpc-interceptor                         0.15.4
grpcio                                   1.81.0
grpcio-status                            1.71.2
grpclib                                  0.4.9
gspread                                  6.2.1
gspread-dataframe                        4.0.0
gym                                      0.25.2
gym-notices                              0.1.0
gymnasium                                1.3.0
h11                                      0.16.0
h2                                       4.3.0
h5netcdf                                 1.8.1
h5py                                     3.16.0
hdbscan                                  0.8.44
hf-xet                                   1.5.1
highspy                                  1.14.0
holidays                                 0.98
holoviews                                1.22.1
hpack                                    4.1.0
html5lib                                 1.1
httpcore                                 1.0.9
httpimport                               1.4.1
httplib2                                 0.31.2
httptools                                0.8.0
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface_hub                          1.18.0
humanize                                 4.15.0
hyperframe                               6.1.0
hyperopt                                 0.2.7
ibis-framework                           9.5.0
idna                                     3.18
ImageIO                                  2.37.3
imageio-ffmpeg                           0.6.0
imagesize                                2.0.0
imbalanced-learn                         0.14.2
immutabledict                            4.3.1
importlib_metadata                       8.7.1
importlib_resources                      7.1.0
imutils                                  0.5.4
inequality                               1.1.2
inflect                                  7.5.0
iniconfig                                2.3.0
intel-cmplr-lib-ur                       2025.3.3
intel-openmp                             2025.3.3
ipyevents                                2.0.4
ipyfilechooser                           0.6.0
ipykernel                                6.17.1
ipyleaflet                               0.20.0
ipyparallel                              8.8.0
ipython                                  7.34.0
ipython-genutils                         0.2.0
ipython-sql                              0.5.0
ipywidgets                               7.7.1
isoduration                              20.11.0
itsdangerous                             2.2.0
jaraco.classes                           3.4.0
jaraco.context                           6.1.2
jaraco.functools                         4.5.0
jax                                      0.7.2
jaxlib                                   0.7.2
jeepney                                  0.9.0
jieba                                    0.42.1
Jinja2                                   3.1.6
jiter                                    0.15.0
joblib                                   1.5.3
joserfc                                  1.7.1
jsonpatch                                1.33
jsonpickle                               4.1.2
jsonpointer                              3.1.1
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
jupyter_client                           7.4.9
jupyter-console                          6.6.3
jupyter_core                             5.9.1
jupyter-events                           0.12.1
jupyter_kernel_gateway                   2.5.2
jupyter-leaflet                          0.20.0
jupyter_server                           2.18.2
jupyter_server_terminals                 0.5.4
jupyterlab_pygments                      0.3.0
jupyterlab_widgets                       3.0.16
jupytext                                 1.19.3
kaggle                                   2.0.2
kagglehub                                1.0.2
kagglesdk                                0.1.23
keras                                    3.13.2
keras-hub                                0.26.0
keras-nlp                                0.26.0
keyring                                  25.7.0
keyrings.google-artifactregistry-auth    1.1.2
kiwisolver                               1.5.0
langchain                                1.3.6
langchain-core                           1.4.3
langchain-protocol                       0.0.16
langgraph                                1.2.4
langgraph-checkpoint                     4.1.1
langgraph-prebuilt                       1.1.0
langgraph-sdk                            0.4.2
langsmith                                0.8.12
lark                                     1.3.1
launchpadlib                             1.10.16
lazr.restfulclient                       0.14.4
lazr.uri                                 1.0.6
lazy-loader                              0.5
libclang                                 18.1.1
libpysal                                 4.14.1
librosa                                  0.11.0
lightgbm                                 4.6.0
linkify-it-py                            2.1.0
llvmlite                                 0.43.0
locket                                   1.0.0
logical-unification                      0.4.7
lxml                                     6.1.1
Mako                                     1.3.12
mapclassify                              2.10.0
Markdown                                 3.10.2
markdown-it-py                           4.2.0
MarkupSafe                               3.0.3
matplotlib                               3.10.0
matplotlib-inline                        0.2.2
matplotlib-venn                          1.1.2
mcp                                      1.27.2
mdit-py-plugins                          0.6.1
mdurl                                    0.1.2
mgwr                                     2.2.1
miniKanren                               1.0.5
missingno                                0.5.2
mistune                                  3.2.1
mizani                                   0.13.5
mkl                                      2025.3.1
ml_dtypes                                0.5.4
mlxtend                                  0.23.4
mmh3                                     5.2.1
momepy                                   0.11.0
more-itertools                           10.8.0
moviepy                                  1.0.3
mpmath                                   1.3.0
msgpack                                  1.1.2
multidict                                6.7.1
multipledispatch                         1.0.0
multiprocess                             0.70.16
multitasking                             0.0.13
murmurhash                               1.0.15
music21                                  9.9.2
namex                                    0.1.0
narwhals                                 2.22.1
natsort                                  8.4.0
nbclassic                                1.3.3
nbclient                                 0.10.4
nbconvert                                7.17.1
nbformat                                 5.10.4
ndindex                                  1.10.1
nest-asyncio                             1.6.0
networkx                                 3.6.1
nh3                                      0.3.5
nibabel                                  5.4.2
nltk                                     3.9.1
notebook                                 6.5.7
notebook_shim                            0.2.4
numba                                    0.60.0
numexpr                                  2.14.1
numpy                                    2.0.2
nvidia-nccl-cu12                         2.30.7
oauth2client                             4.1.3
oauthlib                                 3.3.1
omegaconf                                2.3.0
onemkl-license                           2025.3.1
openai                                   2.41.0
opencv-contrib-python                    4.13.0.92
opencv-python                            4.13.0.92
opencv-python-headless                   4.13.0.92
openpyxl                                 3.1.5
opentelemetry-api                        1.38.0
opentelemetry-exporter-gcp-logging       1.11.0a0
opentelemetry-exporter-gcp-monitoring    1.12.0a0
opentelemetry-exporter-gcp-trace         1.12.0
opentelemetry-exporter-otlp-proto-common 1.38.0
opentelemetry-exporter-otlp-proto-http   1.38.0
opentelemetry-proto                      1.38.0
opentelemetry-resourcedetector-gcp       1.12.0a0
opentelemetry-sdk                        1.38.0
opentelemetry-semantic-conventions       0.59b0
opt_einsum                               3.4.0
optax                                    0.2.8
optree                                   0.19.1
orbax-checkpoint                         0.12.0
orjson                                   3.11.9
ormsgpack                                1.12.2
osqp                                     1.1.2
packaging                                26.2
pandas                                   2.2.2
pandas-datareader                        0.10.0
pandas-gbq                               0.30.0
pandas-stubs                             2.2.2.240909
pandocfilters                            1.5.1
panel                                    1.9.3
panel-material-ui                        0.12.0
param                                    2.4.1
parso                                    0.8.7
parsy                                    2.2
partd                                    1.4.2
patsy                                    1.0.2
peewee                                   4.0.6
peft                                     0.19.1
pexpect                                  4.9.0
pickleshare                              0.7.5
pillow                                   11.3.0
pip                                      24.1.2
platformdirs                             4.10.0
plotly                                   5.24.1
plotnine                                 0.14.5
pluggy                                   1.6.0
plum-dispatch                            2.9.0
pointpats                                2.5.5
polars                                   1.35.2
polars-runtime-32                        1.35.2
pooch                                    1.9.0
portpicker                               1.5.2
preshed                                  3.0.13
prettytable                              3.17.0

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [ ]:
df['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
df.total_bedrooms

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
df.total_bedrooms[0]

np.float64(661.0)

In [ ]:
df['total_bedrooms'][2999]

np.float64(263.0)

In [ ]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.18.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lukebarousse/data_jobs')

In [ ]:
df = dataset['train'].to_pandas()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.head(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,Romania,2023-12-07 13:40:49,False,False,Romania,None,NaN,NaN,Zitec,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,Business Analyst,Technology & Operations Business Analyst,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-06-05 13:44:34,False,False,Denmark,None,NaN,NaN,Hempel,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [ ]:
df.tail(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785731,Data Engineer,Data Engineer,"Overland Park, Kansas, Amerika Serikat",melalui LinkedIn,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:17,False,False,Sudan,None,NaN,NaN,Shamrock Trading Corporation,"['nosql', 'mongodb', 'mongodb', 'python', 'ela...","{'analyst_tools': ['excel'], 'cloud': ['aws', ..."
785732,Data Engineer,Data Engineer (f/m/d),"Heidelberg, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:18:59,False,False,Germany,None,NaN,NaN,Heidelberg Materials,"['python', 'c#', 'java', 'scala', 'sql', 'post...","{'cloud': ['azure', 'databricks'], 'databases'..."
785733,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:17,False,False,Singapore,None,NaN,NaN,Hydra X Pte. Ltd.,"['docker', 'kubernetes']","{'other': ['docker', 'kubernetes']}"
785734,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",melalui Melga,Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,False,False,Kazakhstan,None,NaN,NaN,Staff-UP Consulting Group,['windows'],{'os': ['windows']}
785735,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,None,NaN,NaN,Pure App,"['sql', 'python', 'bigquery', 'aws', 'airflow'...","{'cloud': ['bigquery', 'aws'], 'libraries': ['..."
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df['job_title_short'].head()

0    Senior Data Engineer
1            Data Analyst
2           Data Engineer
3           Data Engineer
4           Data Engineer
Name: job_title_short, dtype: object

In [ ]:
df[['job_title_short', 'job_location']].head()

        job_title_short                  job_location
0  Senior Data Engineer                 Watertown, CT
1          Data Analyst  Guadalajara, Jalisco, Mexico
2         Data Engineer               Berlin, Germany
3         Data Engineer               San Antonio, TX
4         Data Engineer                Washington, DC

In [ ]:
df.iloc[90:100]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
90,Data Scientist,Data Scientist,Australia,via BeBee Australia,Full-time,False,Australia,2023-11-25 13:12:03,False,False,Australia,None,NaN,NaN,Concurrent Technologies Corporation,"['python', 'sql', 'r', 'java', 'bash', 'react'...","{'analyst_tools': ['tableau'], 'libraries': ['..."
91,Data Scientist,Data Scientist,"Temuco, Chile",via BeBee Chile,Full-time,False,Chile,2023-01-06 14:07:40,False,False,Chile,None,NaN,NaN,Talently,"['sql', 'python', 'tensorflow', 'numpy', 'pand...","{'analyst_tools': ['excel', 'tableau'], 'libra..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
93,Data Analyst,IT Finance / TBM Data Analyst - Remote | WFH,Anywhere,via LinkedIn,Full-time,True,"New York, United States",2023-06-10 13:00:05,False,False,United States,None,NaN,NaN,Get It Recruit - Information Technology,"['oracle', 'azure', 'power bi', 'excel', 'word...","{'analyst_tools': ['power bi', 'excel', 'word'..."
94,Data Engineer,Data Engineer - Cloud Operations,"Lehi, UT",via LinkedIn,Full-time,False,"Texas, United States",2023-03-18 13:08:17,False,False,United States,None,NaN,NaN,Adobe,"['javascript', 'python', 'sql', 'aws', 'azure'...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."
95,Data Engineer,Data Engineer,"Mumbai, Maharashtra, India",via Crimsoniteam.freshteam.com,Full-time,False,India,2023-07-31 13:35:48,False,False,India,None,NaN,NaN,Crimson Interactive Inc,"['nosql', 'mongodb', 'mongodb', 'elasticsearch...","{'analyst_tools': ['tableau'], 'databases': ['..."
96,Data Engineer,Data Engineer,"Torrance, CA",via LinkedIn,Full-time,False,Sudan,2023-06-15 14:03:55,False,False,Sudan,None,NaN,NaN,King's Hawaiian,"['sql', 'r', 'python', 'sql server', 'azure', ...","{'analyst_tools': ['sap'], 'cloud': ['azure', ..."
97,Data Analyst,"Systems & Data Analyst - Exploitation, Missing...",United Kingdom,via Totaljobs,Full-time and Contractor,False,United Kingdom,2023-12-04 13:14:01,True,False,United Kingdom,None,NaN,NaN,Solihull Metropolitan Borough Council,None,None
98,Senior Data Engineer,Senior Data Engineer (AWS),"Toronto, ON, Canada",via SmartRecruiters Job Search,Full-time,False,Canada,2023-09-01 13:42:05,True,False,Canada,None,NaN,NaN,MUFG Investor Services,"['python', 'aws', 'databricks', 'spark']","{'cloud': ['aws', 'databricks'], 'libraries': ..."
99,Data Engineer,Senior/Staff Data Engineer – Apache Spark (Jav...,"Miami, FL",via LinkedIn,Full-time,False,"California, United States",2023-09-12 13:09:28,False,False,United States,None,NaN,NaN,Agoda,"['scala', 'java', 'golang', 'sql', 'react', 's...","{'libraries': ['react', 'spark', 'hadoop'], 'o..."

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [ ]:
df.describe()

       salary_year_avg  salary_hour_avg
count     22003.000000     10662.000000
mean     123286.274072        47.016598
std       48312.449482        21.890738
min       15000.000000         8.000000
25%       90000.000000        27.500000
50%      115000.000000        45.980000
75%      150000.000000        61.159996
max      960000.000000       391.000000

In [ ]:
df[['job_title_short', 'job_title']].iloc[90:100]

         job_title_short                                          job_title
90        Data Scientist                                     Data Scientist
91        Data Scientist                                     Data Scientist
92         Data Engineer            Remote - Data Engineer - Permanent - W2
93          Data Analyst       IT Finance / TBM Data Analyst - Remote | WFH
94         Data Engineer                   Data Engineer - Cloud Operations
95         Data Engineer                                      Data Engineer
96         Data Engineer                                      Data Engineer
97          Data Analyst  Systems & Data Analyst - Exploitation, Missing...
98  Senior Data Engineer                         Senior Data Engineer (AWS)
99         Data Engineer  Senior/Staff Data Engineer – Apache Spark (Jav...

In [ ]:
df.job_title_short.unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [ ]:
df[(df.job_title_short == 'Data Analyst') & (df.salary_year_avg > 100000)]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
410,Data Analyst,IT Business Lead Data Analyst - VP - Hybrid,"Atlantic Beach, FL",via ComputerJobs.com,Full-time,False,Georgia,2023-01-10 13:59:02,False,False,United States,year,133285.0,NaN,Citi,"['sql', 'word', 'excel', 'visio', 'powerpoint'...","{'analyst_tools': ['word', 'excel', 'visio', '..."
1555,Data Analyst,Data Analyst/Engineer (M/F/D),"Aveiro, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-04-25 13:27:25,False,False,Portugal,year,111175.0,NaN,Bosch Group,"['databricks', 'spark']","{'cloud': ['databricks'], 'libraries': ['spark']}"
1681,Data Analyst,Data Analyst,"Irvine, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-03-23 13:01:14,False,True,United States,year,111175.0,NaN,Western Digital,"['sql', 'tableau', 'power bi', 'excel']","{'analyst_tools': ['tableau', 'power bi', 'exc..."
1684,Data Analyst,Data Analyst - Data17829,"Tampa, FL",via Indeed,Full-time,False,"Florida, United States",2023-07-18 13:02:09,True,True,United States,year,120000.0,NaN,Acrisure,"['shell', 'sql', 'azure', 'databricks', 'linux']","{'cloud': ['azure', 'databricks'], 'os': ['lin..."
1867,Data Analyst,Data Integration Analyst (West Coast/Chicago),"Chicago, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-07-18 13:01:47,False,False,United States,year,101500.0,NaN,Forsta,"['php', 'python', 'express']","{'programming': ['php', 'python'], 'webframewo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783588,Data Analyst,Data Analytics Manager,"Chicago, IL",via Ladders,Full-time,False,"Illinois, United States",2023-01-09 06:01:18,False,False,United States,year,125000.0,NaN,"United Air Lines, Inc","['sql', 'r', 'python', 'hadoop', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['ha..."
783866,Data Analyst,Lead Credit Bureau Data Analyst,"Des Plaines, IL",via Ladders,Full-time,False,"Illinois, United States",2023-06-02 06:02:06,False,True,United States,year,115000.0,NaN,Discover Financial Services,['unix'],{'os': ['unix']}
784033,Data Analyst,Recruitment Data Analyst,"Mumbai, Maharashtra, India",via Ai-Jobs.net,Full-time,False,India,2023-06-07 06:10:15,False,False,India,year,111175.0,NaN,Framestore,"['power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau']}"
785187,Data Analyst,Data Analyst,"Lisbon, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-07 06:30:33,False,False,Portugal,year,111175.0,NaN,Farfetch,"['sql', 'python', 'r', 'looker']","{'analyst_tools': ['looker'], 'programming': [..."
785515,Data Analyst,Data Analyst,"Bengaluru, Karnataka, India",via Ai-Jobs.net,Full-time,False,India,2023-09-01 06:17:34,False,False,India,year,105000.0,NaN,Myntra,None,None

In [ ]:
df.salary_year_avg.notna()

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: salary_year_avg, Length: 785741, dtype: bool

In [ ]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [ ]:
df['job_posted_month'] = df.job_posted_date.dt.month

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

In [ ]:
df.sort_values(by='job_posted_date', inplace=True)

In [ ]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,NaN,VirtualVocations,None,None,12

In [ ]:
df.drop(labels = 'salary_hour_avg', axis = 1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 89.2+ MB

In [ ]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  object
 14  job_skills             20170 non-null  object
 15  job_type_skills        20170 non-null  object
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB